Migrated all podman environments to build-env

diff --git a/scripts/_/templates/python/build-venv.sh.j2 b/scripts/_/templates/python/build-venv.sh.j2
--- a/scripts/_/templates/python/build-venv.sh.j2
+++ b/scripts/_/templates/python/build-venv.sh.j2
@@ -33,10 +33,6 @@ else
     PY_REQS_ARGS=
 fi
 
-# TODO: Export these?
-PS1_TAG=${PS1_TAG:-"({{ps1_tag}}) "}
-PS1="${PS1_TAG}${PS1:-\$ }"
-
 # Assuming we've already collected.
 PIP_INST_ARGS=${PIP_INST_ARGS:-"--no-index -f ${PYTHON_PKG_PATH}"}
 PYTHON=${PYTHON:-"{{python}}"}
@@ -47,22 +43,20 @@ BUILDER_PATH=${BUILDER_PATH:-"{{builder_path}}"}
 
 # ----- End Of Config -----
 
-# Ensure virtualenv is available.
-echo INSTALL VIRTUALENV: ${PYTHON} -m pip install --upgrade ${PIP_INST_ARGS} virtualenv
-${PYTHON} -m pip install --upgrade ${PIP_INST_ARGS} virtualenv
+# Assuming venv was actually created before the download phase in init-python.
 
-mkdir -p ${PYTHON_VENV_PREFIX}
-if [ ! -e "${PYTHON_VENV_PREFIX}/${ENV_NAME}" ]; then
-  # Note: The following line is the only place we enforce python version for venv.
+# mkdir -p ${PYTHON_VENV_PREFIX}
+# if [ ! -e "${PYTHON_VENV_PREFIX}/${ENV_NAME}" ]; then
+#   # Note: The following line is the only place we enforce python version for venv.
   
-  echo CREATE VENV: ${PYTHON} -m virtualenv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
-  ${PYTHON} -m virtualenv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
-  [ $? -ne 0 ] && { echo "Failed to create venv"; exit 1; }
+#   echo CREATE VENV: ${PYTHON} -m virtualenv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
+#   ${PYTHON} -m virtualenv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
+#   [ $? -ne 0 ] && { echo "Failed to create venv"; exit 1; }
 
   echo "--------------------- Setting Up Base Python Requirements ---------------------"
   ${VENV_PYTHON} -m pip install --upgrade \
     ${PIP_INST_ARGS} ${PY_REQS_ARGS} ${PY_CONSTRAINTS_ARGS}
-fi
+# fi
 
 # We don't activate to maintain cross platform patterns.
 #source ./cache/venv/${ENV_NAME}/bin/activate
diff --git a/scripts/_/templates/python/init-python.sh.j2 b/scripts/_/templates/python/init-python.sh.j2
--- a/scripts/_/templates/python/init-python.sh.j2
+++ b/scripts/_/templates/python/init-python.sh.j2
@@ -16,9 +16,35 @@ PROJ_PATH="{{proj_path}}"
 
 PY_VER="{{py_ver}}"
 PYTHON_PKG_PATH=${PYTHON_PKG_PATH:-"{{python_pkg_path}}"}
-
+PYTHON=${PYTHON:-"{{python}}"}
 PIP_UPSTREAM_VERIFIERS="{{pip_upstream_verifiers}}"
 BUILDER_PATH=${BUILDER_PATH:-"{{builder_path}}"}
+PYTHON_VENV_PREFIX=${PYTHON_VENV_PREFIX:-"{{python_venv_prefix}}"}
+
+# ----- Try one of venv, virtualenv, pipx, or uv to create python virtual environment. -----
+# Note: Intentionally performed before the download phase.
+
+mkdir -p ${PYTHON_VENV_PREFIX}
+if ${PYTHON} -m venv --help &>/dev/null; then
+    echo "CREATE VENV (with venv)": ${PYTHON} -m venv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
+    ${PYTHON} -m venv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
+    [ $? -ne 0 ] && { echo "Failed to create venv with venv"; exit 1; }
+elif ${PYTHON} -m virtualenv --help &>/dev/null; then
+    echo "CREATE VENV (with virtualenv)": ${PYTHON} -m virtualenv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
+    ${PYTHON} -m virtualenv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
+    [ $? -ne 0 ] && { echo "Failed to create venv with virtualenv"; exit 1; }
+elif ${PYTHON} -m pipx --help &>/dev/null; then
+    echo "CREATE VENV (with pipx)": ${PYTHON} -m pipx venv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
+    ${PYTHON} -m pipx venv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
+    [ $? -ne 0 ] && { echo "Failed to create venv with pipx"; exit 1; }
+elif ${PYTHON} -m uv --help &>/dev/null; then
+    echo "CREATE VENV (with uv)": ${PYTHON} -m uv venv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
+    ${PYTHON} -m uv venv ${PYTHON_VENV_PREFIX}/${ENV_NAME}
+    [ $? -ne 0 ] && { echo "Failed to create venv with uv"; exit 1; }
+else
+    echo "You need one of venv, virtualenv, pipx, or uv to setup environment." >&2
+    exit 1
+fi
 
 # ----- Fetch and cache python deps ----
 
